### ISSUE TITLE
Use pythonic configuration for optimizers to allow for user extensions

### ISSUE THREAD

**Issue by frthjf** [iraikov/dmosopt#52]
Currently, the user can specify the objective and initialization methods by simply providing a Python module and object name. However, the optimizer and sampling strategies are [hardcoded](https://github.com/iraikov/dmosopt/blob/main/dmosopt/MOASMO.py#L287).

I wonder if it would make sense to change the semantics of the `optimizer` and `sampling_method` setting to refer to a Python object instead. For example, `"optimizer": "nsga2"` would become `"optimizer": "dmosopt.NSGA2:NSGA2"` etc. In this example, I've used the [entry point](https://setuptools.pypa.io/en/latest/pkg_resources.html#entry-points) notation, but for consistency, it might make more to add a `optimizer_module` option instead.

This would allow users to extend and develop custom strategies by simply pointing to the module. To maintain backward compatibility we could simply keep the current behavior but fall back on importing if the user provides an 'unknown' option.

**Comment by iraikov** [comment]
That's a good idea, that way we don't have to make a new release just to add another optimizer. We should consider doing the same for the surrogate methods, so we don't need to add extra dependencies on GPflow etc.
